print('NaamInvoer')
name = input('Geef jou naam')
print('Hallo ' + name)

print('---------------------------------------------------- ')
print('|  Naam      : Fabian van Zandt                ')
print('|  Adres     : Koekenbakkersplein 23           ')
print('|  Postcode  : 2834 EF                         ')
print('|  Woonplaats: Houten                          ')
print('---------------------------------------------------- ')
