print('NaamInvoer')
name = input('Geef jou naam')
print('Hallo ' + name)
print('Aderesinvoer')
adres = input('Geef jou adres')
print(adres)
print('PostcodeInvoer')
postcode = input ('Geef jou postcode')
print(postcode)
print('WoonplaatsInvoer')
Woonplaats = input ('Geef jou Woonplaats')
print(Woonplaats)

print('----------------------------------------------------')
print('|  Naam      :' + name)               
print('|  Adres     :' + adres)          
print('|  Postcode  :' + postcode)                         
print('|  Woonplaats:' + Woonplaats)                          
print('----------------------------------------------------')
